#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = "master" ] || [ "$branch" = "main" ]; then
  echo "You can't commit directly to master/main branch"
  exit 1
fi

#if [ "$branch" = "develop" ]; then
#  echo "You can't commit directly to master branch"
#  exit 1
#fi
pnpm git-branch-is develop && echo "[🚫 NOT ALLOWED TO COMMIT ON $branch]" && exit 1
pnpm git-branch-is --not master
pnpm git-branch-is --not develop



pnpm test run
